/**
 * Represents a Brazilian holiday.
 *
 * @property date - The date of the holiday in YYYY-MM-DD format
 * @property name - The name of the holiday in Portuguese
 * @property type - The type/scope of the holiday (e.g., 'national', 'municipal')
 */
export type Holiday = {
  date: string;
  name: string;
  type: string;
};

/**
 * Interface defining the contract for holiday-related operations.
 * This allows for different implementations (e.g., static data, API-only, etc.).
 */
interface HolidayHandler {
  getHolidays(year: number): Promise<Holiday[]>;
  isHoliday(date: string): Promise<boolean>;
}

/**
 * Brazilian Holiday handler that provides methods to check and retrieve holiday information.
 *
 * Features:
 * - Static data fallback for common years (current year ±2 years)
 * - Live API integration with Brasil API (https://brasilapi.com.br)
 * - Date validation and error handling
 *
 * Usage:
 * ```typescript
 * // Default mode (uses static data when available)
 * const holidays = new BRHoliday();
 *
 * // Live-only mode (always uses API)
 * const liveHolidays = new BRHoliday({ liveOnly: true });
 * ```
 *
 * @implements {HolidayHandler}
 */
export class BRHoliday implements HolidayHandler {
  /** Cached static holiday data shared across instances */
  private static staticData: Record<number, Holiday[]> | null = null;
  /** Whether to bypass static data and always use the API */
  private liveOnly: boolean;

              /**
   * Static holiday data - dynamic generated by br-holiday in build-time
   * Keep this file in sync with the main script.
   * Generated on 2025-01-21T15:43:07.185Z
   * @internal
   */
  private static staticHolidays: Record<number, Holiday[]> = {
  "2023": [
    {
      "date": "2023-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2023-02-21",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2023-04-07",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2023-04-09",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2023-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2023-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2023-06-08",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2023-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2023-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2023-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2023-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2023-12-25",
      "name": "Natal",
      "type": "national"
    }
  ],
  "2024": [
    {
      "date": "2024-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2024-02-13",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2024-03-29",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2024-03-31",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2024-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2024-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2024-05-30",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2024-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2024-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2024-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2024-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2024-11-20",
      "name": "Dia da consciência negra",
      "type": "national"
    },
    {
      "date": "2024-12-25",
      "name": "Natal",
      "type": "national"
    }
  ],
  "2025": [
    {
      "date": "2025-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2025-03-04",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2025-04-18",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2025-04-20",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2025-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2025-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2025-06-19",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2025-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2025-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2025-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2025-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2025-11-20",
      "name": "Dia da consciência negra",
      "type": "national"
    },
    {
      "date": "2025-12-25",
      "name": "Natal",
      "type": "national"
    }
  ],
  "2026": [
    {
      "date": "2026-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2026-02-17",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2026-04-03",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2026-04-05",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2026-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2026-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2026-06-04",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2026-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2026-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2026-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2026-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2026-11-20",
      "name": "Dia da consciência negra",
      "type": "national"
    },
    {
      "date": "2026-12-25",
      "name": "Natal",
      "type": "national"
    }
  ],
  "2027": [
    {
      "date": "2027-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2027-02-09",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2027-03-26",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2027-03-28",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2027-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2027-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2027-05-27",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2027-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2027-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2027-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2027-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2027-11-20",
      "name": "Dia da consciência negra",
      "type": "national"
    },
    {
      "date": "2027-12-25",
      "name": "Natal",
      "type": "national"
    }
  ]
};










  /**
   * Creates a new BRHoliday instance.
   *
   * @param options - Configuration options
   * @param options.liveOnly - If true, always uses the API instead of static data
   */
  constructor(options?: { liveOnly?: boolean }) {
    this.liveOnly = options?.liveOnly ?? false;
  }

  /**
   * Retrieves all holidays for a specific year.
   * First attempts to use static data (if available and not in live-only mode),
   * then falls back to the API.
   *
   * @param year - The year to get holidays for
   * @returns Promise resolving to an array of holidays
   */
  async getHolidays(year: number): Promise<Holiday[]> {
    if (BRHoliday.staticHolidays[year]) {
      return BRHoliday.staticHolidays[year];
    }

    const holidays = await fetch(
      `https://brasilapi.com.br/api/feriados/v1/${year}`
    );
    const data = await holidays.json();
    return data;
  }

  /**
   * Checks if a specific date is a holiday.
   *
   * @param date - The date to check in YYYY-MM-DD format
   * @returns Promise resolving to true if the date is a holiday, false otherwise
   * @throws {Error} If the date format is invalid
   */
  async isHoliday(date: string): Promise<boolean> {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
      throw new Error("Invalid date format. Use YYYY-MM-DD");
    }

    const year = parseInt(date.split("-")[0]);
    const holidays = await this.getHolidays(year);
    return holidays.some((holiday) => holiday.date === date);
  }
  // <<HOLIDAYS_DATA>>
}
