import type { Holiday } from './types';

/**
 * Static holiday data generated at build time
 * This file is automatically generated by scripts/generate-static.js
 * DO NOT EDIT MANUALLY
 * 
 * Generated on: 2025-07-20
 * Years included: 2025, 2026
 */
export const STATIC_HOLIDAYS: Readonly<Record<number, Holiday[]>> = Object.freeze({
  "2025": [
    {
      "date": "2025-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2025-03-04",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2025-04-18",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2025-04-20",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2025-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2025-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2025-06-19",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2025-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2025-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2025-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2025-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2025-11-20",
      "name": "Dia da consciência negra",
      "type": "national"
    },
    {
      "date": "2025-12-25",
      "name": "Natal",
      "type": "national"
    }
  ],
  "2026": [
    {
      "date": "2026-01-01",
      "name": "Confraternização mundial",
      "type": "national"
    },
    {
      "date": "2026-02-17",
      "name": "Carnaval",
      "type": "national"
    },
    {
      "date": "2026-04-03",
      "name": "Sexta-feira Santa",
      "type": "national"
    },
    {
      "date": "2026-04-05",
      "name": "Páscoa",
      "type": "national"
    },
    {
      "date": "2026-04-21",
      "name": "Tiradentes",
      "type": "national"
    },
    {
      "date": "2026-05-01",
      "name": "Dia do trabalho",
      "type": "national"
    },
    {
      "date": "2026-06-04",
      "name": "Corpus Christi",
      "type": "national"
    },
    {
      "date": "2026-09-07",
      "name": "Independência do Brasil",
      "type": "national"
    },
    {
      "date": "2026-10-12",
      "name": "Nossa Senhora Aparecida",
      "type": "national"
    },
    {
      "date": "2026-11-02",
      "name": "Finados",
      "type": "national"
    },
    {
      "date": "2026-11-15",
      "name": "Proclamação da República",
      "type": "national"
    },
    {
      "date": "2026-11-20",
      "name": "Dia da consciência negra",
      "type": "national"
    },
    {
      "date": "2026-12-25",
      "name": "Natal",
      "type": "national"
    }
  ]
});